import customtkinter as ctk
from datetime import datetime
from tkinter import messagebox


from app.services.dashboard_service import DashboardService


class DashboardFrame(ctk.CTkFrame):
    """
    Q02 Hospital Operations Dashboard.

    Design principle:
        See the situation -> understand the bottleneck -> take action.

    Every clinical/operational number displayed here comes from the live
    SQLite database through DashboardService. No fabricated history or
    placeholder hospital data is generated by the dashboard.
    """

    BACKGROUND = "#F6F8FC"
    CARD = "#FFFFFF"
    CARD_SOFT = "#F8FAFC"
    BORDER = "#E5EAF0"

    TEXT = "#0F172A"
    SECONDARY = "#64748B"
    MUTED = "#94A3B8"

    BLUE = "#2563EB"
    BLUE_DARK = "#1D4ED8"
    BLUE_SOFT = "#EFF6FF"

    GREEN = "#10B981"
    GREEN_DARK = "#047857"
    GREEN_SOFT = "#ECFDF5"

    AMBER = "#F59E0B"
    AMBER_DARK = "#B45309"
    AMBER_SOFT = "#FFFBEB"

    RED = "#EF4444"
    RED_DARK = "#B91C1C"
    RED_SOFT = "#FEF2F2"

    PURPLE = "#7C3AED"
    PURPLE_SOFT = "#F5F3FF"

    CYAN = "#0891B2"
    CYAN_SOFT = "#ECFEFF"

    def __init__(self, parent, user=None):
        super().__init__(
            parent,
            fg_color=self.BACKGROUND,
            corner_radius=0
        )

        self.user = user or {
            "username": "admin",
            "role": "admin"
        }

        self.service = DashboardService()
        self.metrics = {}

        self.value_labels = {}
        self.status_labels = {}
        self.queue_frame = None
        self.ward_frame = None
        self.flow_canvas = None
        self.bed_canvas = None
        self.refresh_button = None
        self.last_refresh_label = None

        self.window = self.winfo_toplevel()

        self.create_widgets()

    # =========================================================
    # BUILD
    # =========================================================

    def create_widgets(self):
        self.main = ctk.CTkScrollableFrame(
            self,
            fg_color=self.BACKGROUND,
            corner_radius=0,
            scrollbar_button_color="#CBD5E1",
            scrollbar_button_hover_color="#94A3B8"
        )
        self.main.pack(fill="both", expand=True)

        self.load_metrics()

        self.create_header()
        self.create_kpi_row()
        self.create_operational_row()
        self.create_capacity_and_quality_row()
        self.create_quick_actions()
        self.create_footer()

    # =========================================================
    # DATA
    # =========================================================

    def load_metrics(self):
        try:
            self.metrics = self.service.get_dashboard_metrics()

        except Exception as error:
            messagebox.showerror(
                "Dashboard Error",
                f"Unable to load hospital dashboard data.\n\n{error}"
            )
            self.metrics = {
                "today_patients": 0,
                "today_appointments": 0,
                "pending_appointments": 0,
                "completed_appointments": 0,
                "cancelled_appointments": 0,
                "checked_in_appointments": 0,
                "measured_waits": 0,
                "average_waiting_seconds": 0,
                "total_beds": 0,
                "occupied_beds": 0,
                "available_beds": 0,
                "queue": [],
                "bed_wards": [],
                "latest_patients": []
            }

    # =========================================================
    # HEADER
    # =========================================================

    def create_header(self):
        header = ctk.CTkFrame(
            self.main,
            fg_color=self.CARD,
            corner_radius=20,
            border_width=1,
            border_color=self.BORDER
        )
        header.pack(
            fill="x",
            padx=30,
            pady=(24, 14)
        )

        header.grid_columnconfigure(0, weight=1)
        header.grid_columnconfigure(1, weight=0)

        left = ctk.CTkFrame(
            header,
            fg_color="transparent"
        )
        left.grid(
            row=0,
            column=0,
            sticky="w",
            padx=24,
            pady=21
        )

        ctk.CTkLabel(
            left,
            text="HOSPITAL OPERATIONS",
            text_color=self.BLUE,
            font=ctk.CTkFont(size=9, weight="bold")
        ).pack(anchor="w")

        username = str(
            self.user.get("username", "admin")
        ).strip().title()

        ctk.CTkLabel(
            left,
            text=f"Good day, {username}",
            text_color=self.TEXT,
            font=ctk.CTkFont(size=27, weight="bold")
        ).pack(anchor="w", pady=(3, 0))

        today = datetime.now().strftime("%A, %d %B %Y")
        ctk.CTkLabel(
            left,
            text=f"{today}  •  Live operational overview",
            text_color=self.SECONDARY,
            font=ctk.CTkFont(size=10)
        ).pack(anchor="w", pady=(4, 0))

        right = ctk.CTkFrame(
            header,
            fg_color="transparent"
        )
        right.grid(
            row=0,
            column=1,
            sticky="e",
            padx=24,
            pady=21
        )

        role = str(
            self.user.get("role", "admin")
        ).lower()

        role_soft = self.GREEN_SOFT if role == "staff" else self.BLUE_SOFT
        role_text = self.GREEN_DARK if role == "staff" else self.BLUE

        role_pill = ctk.CTkLabel(
            right,
            text=f"  {role.upper()} WORKSPACE  ",
            fg_color=role_soft,
            text_color=role_text,
            corner_radius=8,
            font=ctk.CTkFont(size=8, weight="bold")
        )
        role_pill.pack(side="left", padx=(0, 8))

        q02_pill = ctk.CTkLabel(
            right,
            text="  Q02 • IMPROVE PERFORMANCE  ",
            fg_color=self.PURPLE_SOFT,
            text_color=self.PURPLE,
            corner_radius=8,
            font=ctk.CTkFont(size=8, weight="bold")
        )
        q02_pill.pack(side="left", padx=(0, 8))

        self.refresh_button = ctk.CTkButton(
            right,
            text="↻  Refresh",
            width=105,
            height=36,
            corner_radius=10,
            fg_color=self.BLUE,
            hover_color=self.BLUE_DARK,
            command=self.refresh_dashboard
        )
        self.refresh_button.pack(side="left")

    # =========================================================
    # KPI ROW
    # =========================================================

    def create_kpi_row(self):
        row = ctk.CTkFrame(
            self.main,
            fg_color="transparent"
        )
        row.pack(
            fill="x",
            padx=30,
            pady=(0, 15)
        )

        for column in range(4):
            row.grid_columnconfigure(
                column,
                weight=1,
                uniform="kpi"
            )

        cards = [
            (
                "TODAY'S PATIENTS",
                self.metrics["today_patients"],
                "Registrations today",
                "♙",
                self.BLUE,
                self.BLUE_SOFT
            ),
            (
                "TODAY'S APPOINTMENTS",
                self.metrics["today_appointments"],
                "Scheduled for today",
                "◷",
                self.PURPLE,
                self.PURPLE_SOFT
            ),
            (
                "WAITING QUEUE",
                self.metrics["pending_appointments"],
                "Still scheduled",
                "≡",
                self.AMBER,
                self.AMBER_SOFT
            ),
            (
                "AVERAGE WAIT",
                self.service.format_waiting_time(
                    self.metrics["average_waiting_seconds"]
                ),
                (
                    f"Based on {self.metrics['measured_waits']} "
                    "measured visit(s)"
                ),
                "⌛",
                self.GREEN,
                self.GREEN_SOFT
            )
        ]

        for column, data in enumerate(cards):
            self.create_kpi_card(row, data, column)

    def create_kpi_card(self, parent, data, column):
        title, value, caption, icon, accent, soft = data

        card = ctk.CTkFrame(
            parent,
            fg_color=self.CARD,
            corner_radius=17,
            border_width=1,
            border_color=self.BORDER
        )
        card.grid(
            row=0,
            column=column,
            padx=(0 if column == 0 else 5, 5 if column < 3 else 0),
            sticky="nsew"
        )

        top = ctk.CTkFrame(
            card,
            fg_color="transparent"
        )
        top.pack(
            fill="x",
            padx=16,
            pady=(15, 8)
        )

        icon_box = ctk.CTkFrame(
            top,
            width=34,
            height=34,
            corner_radius=10,
            fg_color=soft
        )
        icon_box.pack_propagate(False)
        icon_box.pack(side="left")

        ctk.CTkLabel(
            icon_box,
            text=icon,
            text_color=accent,
            font=ctk.CTkFont(size=15, weight="bold")
        ).pack(expand=True)

        ctk.CTkLabel(
            top,
            text=title,
            text_color=self.MUTED,
            font=ctk.CTkFont(size=8, weight="bold")
        ).pack(
            side="left",
            padx=(9, 0)
        )

        value_label = ctk.CTkLabel(
            card,
            text=str(value),
            text_color=self.TEXT,
            font=ctk.CTkFont(size=23, weight="bold")
        )
        value_label.pack(
            anchor="w",
            padx=16,
            pady=(1, 0)
        )

        ctk.CTkLabel(
            card,
            text=caption,
            text_color=self.SECONDARY,
            font=ctk.CTkFont(size=8)
        ).pack(
            anchor="w",
            padx=16,
            pady=(2, 15)
        )

    # =========================================================
    # OPERATIONAL ROW
    # =========================================================

    def create_operational_row(self):
        row = ctk.CTkFrame(
            self.main,
            fg_color="transparent"
        )
        row.pack(
            fill="x",
            padx=30,
            pady=(0, 15)
        )

        row.grid_columnconfigure(
            0,
            weight=7,
            uniform="operations"
        )
        row.grid_columnconfigure(
            1,
            weight=3,
            uniform="operations"
        )

        self.create_flow_panel(row)
        self.create_bed_panel(row)

    def create_flow_panel(self, parent):
        card = ctk.CTkFrame(
            parent,
            fg_color=self.CARD,
            corner_radius=18,
            border_width=1,
            border_color=self.BORDER
        )
        card.grid(
            row=0,
            column=0,
            padx=(0, 7),
            sticky="nsew"
        )

        header = ctk.CTkFrame(
            card,
            fg_color="transparent"
        )
        header.pack(
            fill="x",
            padx=20,
            pady=(17, 4)
        )

        title_area = ctk.CTkFrame(
            header,
            fg_color="transparent"
        )
        title_area.pack(side="left")

        ctk.CTkLabel(
            title_area,
            text="Today's patient flow",
            text_color=self.TEXT,
            font=ctk.CTkFont(size=15, weight="bold")
        ).pack(anchor="w")

        ctk.CTkLabel(
            title_area,
            text="Appointment status is the operational picture for today",
            text_color=self.SECONDARY,
            font=ctk.CTkFont(size=9)
        ).pack(anchor="w", pady=(2, 0))

        self.flow_canvas = ctk.CTkCanvas(
            card,
            height=210,
            bg=self.CARD,
            highlightthickness=0,
            bd=0
        )
        self.flow_canvas.pack(
            fill="x",
            padx=18,
            pady=(4, 14)
        )

        self.flow_canvas.bind(
            "<Configure>",
            lambda _event: self.draw_flow()
        )
        self.after(60, self.draw_flow)

    def draw_flow(self):
        if self.flow_canvas is None:
            return

        canvas = self.flow_canvas
        width = max(canvas.winfo_width(), 520)
        height = max(canvas.winfo_height(), 190)

        canvas.delete("all")

        values = [
            (
                "Scheduled",
                int(self.metrics.get("pending_appointments", 0)),
                self.AMBER
            ),
            (
                "Checked in",
                int(self.metrics.get("checked_in_appointments", 0)),
                self.CYAN
            ),
            (
                "Completed",
                int(self.metrics.get("completed_appointments", 0)),
                self.GREEN
            ),
            (
                "Cancelled",
                int(self.metrics.get("cancelled_appointments", 0)),
                self.RED
            )
        ]

        maximum = max(
            [value for _, value, _ in values] + [1]
        )

        left = 42
        right = width - 24
        top = 16
        bottom = height - 42
        chart_height = bottom - top
        group_width = (right - left) / len(values)

        for step in range(4):
            ratio = step / 3
            y = bottom - chart_height * ratio

            canvas.create_line(
                left,
                y,
                right,
                y,
                fill="#EEF2F7",
                width=1
            )

            canvas.create_text(
                left - 9,
                y,
                text=str(int(maximum * ratio)),
                fill=self.MUTED,
                font=("Segoe UI", 8),
                anchor="e"
            )

        for index, (label, value, color) in enumerate(values):
            center = left + group_width * index + group_width / 2
            bar_width = min(62, group_width * 0.45)
            bar_height = (
                (value / maximum) * chart_height
                if maximum
                else 0
            )

            canvas.create_rectangle(
                center - bar_width / 2,
                top,
                center + bar_width / 2,
                bottom,
                fill="#F3F6FA",
                outline=""
            )

            canvas.create_rectangle(
                center - bar_width / 2,
                bottom - bar_height,
                center + bar_width / 2,
                bottom,
                fill=color,
                outline=""
            )

            canvas.create_text(
                center,
                bottom - bar_height - 10,
                text=str(value),
                fill=self.TEXT,
                font=("Segoe UI", 9, "bold")
            )

            canvas.create_text(
                center,
                bottom + 20,
                text=label,
                fill=self.SECONDARY,
                font=("Segoe UI", 8)
            )

    # =========================================================
    # BED CAPACITY
    # =========================================================

    def create_bed_panel(self, parent):
        card = ctk.CTkFrame(
            parent,
            fg_color=self.CARD,
            corner_radius=18,
            border_width=1,
            border_color=self.BORDER
        )
        card.grid(
            row=0,
            column=1,
            padx=(7, 0),
            sticky="nsew"
        )

        header = ctk.CTkFrame(
            card,
            fg_color="transparent"
        )
        header.pack(
            fill="x",
            padx=20,
            pady=(17, 4)
        )

        ctk.CTkLabel(
            header,
            text="Bed capacity",
            text_color=self.TEXT,
            font=ctk.CTkFont(size=15, weight="bold")
        ).pack(anchor="w")

        ctk.CTkLabel(
            header,
            text="Current hospital capacity",
            text_color=self.SECONDARY,
            font=ctk.CTkFont(size=9)
        ).pack(anchor="w", pady=(2, 0))

        total = int(self.metrics.get("total_beds", 0))
        occupied = int(self.metrics.get("occupied_beds", 0))
        available = int(self.metrics.get("available_beds", 0))

        percentage = self.service.get_bed_occupancy_percentage(
            occupied,
            total
        )
        status, status_kind = self.service.get_occupancy_status(
            occupied,
            total
        )

        self.bed_canvas = ctk.CTkCanvas(
            card,
            width=190,
            height=125,
            bg=self.CARD,
            highlightthickness=0
        )
        self.bed_canvas.pack(
            fill="x",
            pady=(8, 0)
        )

        self.draw_bed_ring(percentage)

        stat_row = ctk.CTkFrame(
            card,
            fg_color="transparent"
        )
        stat_row.pack(
            fill="x",
            padx=18,
            pady=(2, 8)
        )

        self.create_small_stat(
            stat_row,
            "OCCUPIED",
            occupied,
            self.GREEN
        )
        self.create_small_stat(
            stat_row,
            "AVAILABLE",
            available,
            self.BLUE
        )
        self.create_small_stat(
            stat_row,
            "TOTAL",
            total,
            self.SECONDARY
        )

        status_colors = {
            "success": (self.GREEN_SOFT, self.GREEN_DARK),
            "warning": (self.AMBER_SOFT, self.AMBER_DARK),
            "danger": (self.RED_SOFT, self.RED_DARK)
        }
        soft, fg = status_colors[status_kind]

        ctk.CTkLabel(
            card,
            text=f"  {status}  ",
            fg_color=soft,
            text_color=fg,
            corner_radius=8,
            font=ctk.CTkFont(size=8, weight="bold")
        ).pack(
            anchor="w",
            padx=18,
            pady=(0, 9)
        )

        wards = self.metrics.get("bed_wards", [])
        if wards:
            ctk.CTkLabel(
                card,
                text="BY WARD",
                text_color=self.MUTED,
                font=ctk.CTkFont(size=7, weight="bold")
            ).pack(
                anchor="w",
                padx=18,
                pady=(0, 4)
            )

            for ward in wards[:3]:
                ward_name = str(ward["ward"])
                ward_total = int(ward["total_beds"] or 0)
                ward_occupied = int(ward["occupied_beds"] or 0)
                ward_ratio = (
                    ward_occupied / ward_total
                    if ward_total
                    else 0
                )

                ward_row = ctk.CTkFrame(
                    card,
                    fg_color="transparent"
                )
                ward_row.pack(
                    fill="x",
                    padx=18,
                    pady=2
                )

                ctk.CTkLabel(
                    ward_row,
                    text=ward_name,
                    text_color=self.SECONDARY,
                    font=ctk.CTkFont(size=7, weight="bold")
                ).pack(side="left")

                ctk.CTkLabel(
                    ward_row,
                    text=f"{ward_occupied}/{ward_total}",
                    text_color=self.TEXT,
                    font=ctk.CTkFont(size=7, weight="bold")
                ).pack(side="right")

                track = ctk.CTkProgressBar(
                    card,
                    height=5,
                    corner_radius=3,
                    fg_color="#E9EEF5",
                    progress_color=self.GREEN if ward_ratio < 0.85 else self.AMBER if ward_ratio < 0.95 else self.RED
                )
                track.pack(
                    fill="x",
                    padx=18,
                    pady=(0, 3)
                )
                track.set(ward_ratio)

        ctk.CTkLabel(
            card,
            text="",
            font=ctk.CTkFont(size=1)
        ).pack(pady=(0, 4))

    def draw_bed_ring(self, percentage):
        canvas = self.bed_canvas

        width = max(canvas.winfo_width(), 190)
        center_x = width / 2
        center_y = 58
        radius = 42

        canvas.delete("all")

        canvas.create_arc(
            center_x - radius,
            center_y - radius,
            center_x + radius,
            center_y + radius,
            start=0,
            extent=359,
            style="arc",
            outline="#E9EEF5",
            width=11
        )

        extent = min(359, 359 * percentage / 100)

        canvas.create_arc(
            center_x - radius,
            center_y - radius,
            center_x + radius,
            center_y + radius,
            start=90,
            extent=-extent,
            style="arc",
            outline=self.GREEN if percentage < 85 else self.AMBER if percentage < 95 else self.RED,
            width=11
        )

        canvas.create_text(
            center_x,
            center_y - 2,
            text=f"{percentage:.1f}%",
            fill=self.TEXT,
            font=("Segoe UI", 18, "bold")
        )

        canvas.create_text(
            center_x,
            center_y + 19,
            text="occupied",
            fill=self.MUTED,
            font=("Segoe UI", 8)
        )

    def create_small_stat(self, parent, title, value, accent):
        block = ctk.CTkFrame(
            parent,
            fg_color="transparent"
        )
        block.pack(
            side="left",
            fill="x",
            expand=True
        )

        ctk.CTkLabel(
            block,
            text=title,
            text_color=self.MUTED,
            font=ctk.CTkFont(size=7, weight="bold")
        ).pack(anchor="w")

        ctk.CTkLabel(
            block,
            text=str(value),
            text_color=accent,
            font=ctk.CTkFont(size=16, weight="bold")
        ).pack(anchor="w", pady=(1, 0))

    # =========================================================
    # QUEUE + QUALITY
    # =========================================================

    def create_capacity_and_quality_row(self):
        row = ctk.CTkFrame(
            self.main,
            fg_color="transparent"
        )
        row.pack(
            fill="x",
            padx=30,
            pady=(0, 15)
        )

        row.grid_columnconfigure(
            0,
            weight=7,
            uniform="lower"
        )
        row.grid_columnconfigure(
            1,
            weight=3,
            uniform="lower"
        )

        self.create_queue_panel(row)
        self.create_quality_panel(row)

    def create_queue_panel(self, parent):
        card = ctk.CTkFrame(
            parent,
            fg_color=self.CARD,
            corner_radius=18,
            border_width=1,
            border_color=self.BORDER
        )
        card.grid(
            row=0,
            column=0,
            padx=(0, 7),
            sticky="nsew"
        )

        header = ctk.CTkFrame(
            card,
            fg_color="transparent"
        )
        header.pack(
            fill="x",
            padx=20,
            pady=(17, 7)
        )

        left = ctk.CTkFrame(
            header,
            fg_color="transparent"
        )
        left.pack(side="left")

        ctk.CTkLabel(
            left,
            text="Today's appointment queue",
            text_color=self.TEXT,
            font=ctk.CTkFont(size=15, weight="bold")
        ).pack(anchor="w")

        ctk.CTkLabel(
            left,
            text="Prioritize scheduled and checked-in visits first",
            text_color=self.SECONDARY,
            font=ctk.CTkFont(size=9)
        ).pack(anchor="w", pady=(2, 0))

        ctk.CTkButton(
            header,
            text="Open appointments  →",
            width=145,
            height=31,
            corner_radius=9,
            fg_color=self.BLUE_SOFT,
            hover_color="#DBEAFE",
            text_color=self.BLUE_DARK,
            font=ctk.CTkFont(size=8, weight="bold"),
            command=self.go_appointments
        ).pack(side="right")

        self.queue_frame = ctk.CTkFrame(
            card,
            fg_color="transparent"
        )
        self.queue_frame.pack(
            fill="x",
            padx=14,
            pady=(0, 14)
        )

        self.render_queue()

    def render_queue(self):
        for widget in self.queue_frame.winfo_children():
            widget.destroy()

        queue = self.metrics.get("queue", [])

        if not queue:
            empty = ctk.CTkFrame(
                self.queue_frame,
                fg_color=self.CARD_SOFT,
                corner_radius=12
            )
            empty.pack(fill="x", padx=6, pady=6)

            ctk.CTkLabel(
                empty,
                text="No appointments are scheduled for today.",
                text_color=self.SECONDARY,
                font=ctk.CTkFont(size=10)
            ).pack(pady=18)

            return

        columns = [
            ("TIME", 0.14),
            ("PATIENT", 0.28),
            ("DOCTOR", 0.28),
            ("STATUS", 0.20)
        ]

        header = ctk.CTkFrame(
            self.queue_frame,
            fg_color="#F8FAFC",
            corner_radius=8
        )
        header.pack(fill="x", padx=6, pady=(0, 3))

        for label, rel in columns:
            ctk.CTkLabel(
                header,
                text=label,
                text_color=self.MUTED,
                font=ctk.CTkFont(size=7, weight="bold")
            ).place(
                relx=sum(x[1] for x in columns[:columns.index((label, rel))]),
                rely=0.5,
                anchor="w"
            )

        for item in queue:
            self.create_queue_row(item)

    def create_queue_row(self, item):
        row = ctk.CTkFrame(
            self.queue_frame,
            fg_color=self.CARD_SOFT,
            corner_radius=9,
            border_width=1,
            border_color="#EDF1F5"
        )
        row.pack(
            fill="x",
            padx=6,
            pady=2
        )

        time_text = str(item["appointment_time"])[:5]
        patient = str(item["patient_name"])
        doctor = str(item["doctor_name"])
        status = str(item["status"])

        if len(patient) > 24:
            patient = patient[:23] + "…"

        if len(doctor) > 22:
            doctor = doctor[:21] + "…"

        status_map = {
            "Scheduled": (self.AMBER_SOFT, self.AMBER_DARK),
            "Checked In": (self.CYAN_SOFT, self.CYAN),
            "Completed": (self.GREEN_SOFT, self.GREEN_DARK),
            "Cancelled": (self.RED_SOFT, self.RED_DARK)
        }
        soft, fg = status_map.get(
            status,
            (self.BLUE_SOFT, self.BLUE_DARK)
        )

        values = [
            (time_text, self.TEXT, 0.03),
            (patient, self.TEXT, 0.17),
            (doctor, self.SECONDARY, 0.45)
        ]

        for text, color, relx in values:
            ctk.CTkLabel(
                row,
                text=text,
                text_color=color,
                font=ctk.CTkFont(size=8, weight="bold" if relx == 0.03 else "normal")
            ).place(
                relx=relx,
                rely=0.5,
                anchor="w"
            )

        ctk.CTkLabel(
            row,
            text=f"  {status}  ",
            fg_color=soft,
            text_color=fg,
            corner_radius=7,
            font=ctk.CTkFont(size=7, weight="bold")
        ).place(
            relx=0.74,
            rely=0.5,
            anchor="w"
        )

        ctk.CTkLabel(
            row,
            text=f"#{item['appointment_id']}",
            text_color=self.MUTED,
            font=ctk.CTkFont(size=7)
        ).place(
            relx=0.96,
            rely=0.5,
            anchor="e"
        )

        row.configure(height=35)
        row.pack_propagate(False)

    def create_quality_panel(self, parent):
        card = ctk.CTkFrame(
            parent,
            fg_color=self.CARD,
            corner_radius=18,
            border_width=1,
            border_color=self.BORDER
        )
        card.grid(
            row=0,
            column=1,
            padx=(7, 0),
            sticky="nsew"
        )

        ctk.CTkLabel(
            card,
            text="Q02 performance control",
            text_color=self.TEXT,
            font=ctk.CTkFont(size=15, weight="bold")
        ).pack(
            anchor="w",
            padx=20,
            pady=(17, 2)
        )

        ctk.CTkLabel(
            card,
            text="The dashboard is the control point for the SRS goal.",
            text_color=self.SECONDARY,
            font=ctk.CTkFont(size=9),
            wraplength=280,
            justify="left"
        ).pack(
            anchor="w",
            padx=20,
            pady=(0, 12)
        )

        checks = [
            (
                "Fast Search",
                "Indexed patient search",
                self.BLUE,
                "✓"
            ),
            (
                "Optimized Reports",
                "Filtered and aggregated SQL",
                self.PURPLE,
                "✓"
            ),
            (
                "CSV Import",
                "Bulk validation workflow",
                self.CYAN,
                "✓"
            ),
            (
                "Efficient Queries",
                "Focused SQLite retrieval",
                self.GREEN,
                "✓"
            )
        ]

        for title, subtitle, accent, icon in checks:
            row = ctk.CTkFrame(
                card,
                fg_color="#F8FAFC",
                corner_radius=9
            )
            row.pack(
                fill="x",
                padx=15,
                pady=3
            )

            badge = ctk.CTkFrame(
                row,
                width=26,
                height=26,
                corner_radius=8,
                fg_color=accent
            )
            badge.pack_propagate(False)
            badge.pack(
                side="left",
                padx=(7, 8),
                pady=7
            )

            ctk.CTkLabel(
                badge,
                text=icon,
                text_color="#FFFFFF",
                font=ctk.CTkFont(size=10, weight="bold")
            ).pack(expand=True)

            text_area = ctk.CTkFrame(
                row,
                fg_color="transparent"
            )
            text_area.pack(
                side="left",
                fill="x",
                expand=True,
                pady=6
            )

            ctk.CTkLabel(
                text_area,
                text=title,
                text_color=self.TEXT,
                font=ctk.CTkFont(size=8, weight="bold")
            ).pack(anchor="w")

            ctk.CTkLabel(
                text_area,
                text=subtitle,
                text_color=self.MUTED,
                font=ctk.CTkFont(size=7)
            ).pack(anchor="w", pady=(1, 0))

        wait = int(self.metrics.get("average_waiting_seconds", 0))
        wait_status, wait_kind = self.service.get_wait_status(wait)

        wait_colors = {
            "success": (self.GREEN_SOFT, self.GREEN_DARK),
            "warning": (self.AMBER_SOFT, self.AMBER_DARK),
            "danger": (self.RED_SOFT, self.RED_DARK)
        }
        soft, fg = wait_colors[wait_kind]

        wait_box = ctk.CTkFrame(
            card,
            fg_color=soft,
            corner_radius=10
        )
        wait_box.pack(
            fill="x",
            padx=15,
            pady=(10, 15)
        )

        ctk.CTkLabel(
            wait_box,
            text="WAITING-TIME SIGNAL",
            text_color=fg,
            font=ctk.CTkFont(size=7, weight="bold")
        ).pack(
            anchor="w",
            padx=10,
            pady=(8, 1)
        )

        ctk.CTkLabel(
            wait_box,
            text=f"{wait_status}  •  {self.service.format_waiting_time(wait)}",
            text_color=fg,
            font=ctk.CTkFont(size=10, weight="bold")
        ).pack(
            anchor="w",
            padx=10,
            pady=(0, 8)
        )

    # =========================================================
    # QUICK ACTIONS
    # =========================================================

    def create_quick_actions(self):
        card = ctk.CTkFrame(
            self.main,
            fg_color=self.CARD,
            corner_radius=18,
            border_width=1,
            border_color=self.BORDER
        )
        card.pack(
            fill="x",
            padx=30,
            pady=(0, 15)
        )

        header = ctk.CTkFrame(
            card,
            fg_color="transparent"
        )
        header.pack(
            fill="x",
            padx=20,
            pady=(15, 8)
        )

        ctk.CTkLabel(
            header,
            text="Common actions",
            text_color=self.TEXT,
            font=ctk.CTkFont(size=14, weight="bold")
        ).pack(side="left")

        ctk.CTkLabel(
            header,
            text="Go directly to the next operational task",
            text_color=self.SECONDARY,
            font=ctk.CTkFont(size=8)
        ).pack(side="left", padx=(9, 0))

        actions = [
            ("♙", "Register patient", "Add a new patient record", self.BLUE, self.go_patients),
            ("◷", "Book appointment", "Schedule a patient visit", self.PURPLE, self.go_appointments),
            ("▤", "Open reports", "Review operational reports", self.CYAN, self.go_reports),
            ("⌁", "Run Q02 test", "Measure performance", self.GREEN, self.go_performance)
        ]

        action_row = ctk.CTkFrame(
            card,
            fg_color="transparent"
        )
        action_row.pack(
            fill="x",
            padx=14,
            pady=(0, 15)
        )

        for column, data in enumerate(actions):
            action_row.grid_columnconfigure(
                column,
                weight=1
            )
            icon, title, subtitle, accent, command = data

            button = ctk.CTkButton(
                action_row,
                text=f"{icon}  {title}\n{subtitle}",
                height=58,
                corner_radius=11,
                fg_color="#F8FAFC",
                hover_color="#EEF2F7",
                border_width=1,
                border_color=self.BORDER,
                text_color=self.TEXT,
                font=ctk.CTkFont(size=9, weight="bold"),
                command=command
            )
            button.grid(
                row=0,
                column=column,
                padx=5,
                sticky="ew"
            )

    # =========================================================
    # FOOTER / NAVIGATION
    # =========================================================

    def create_footer(self):
        footer = ctk.CTkFrame(
            self.main,
            fg_color="transparent"
        )
        footer.pack(
            fill="x",
            padx=30,
            pady=(0, 24)
        )

        ctk.CTkLabel(
            footer,
            text="Q02 • Improve Performance",
            text_color=self.BLUE,
            font=ctk.CTkFont(size=8, weight="bold")
        ).pack(side="left")

        self.last_refresh_label = ctk.CTkLabel(
            footer,
            text=self.get_refresh_text(),
            text_color=self.MUTED,
            font=ctk.CTkFont(size=8)
        )
        self.last_refresh_label.pack(side="right")

    def get_refresh_text(self):
        return (
            "Live SQLite data • refreshed "
            + datetime.now().strftime("%H:%M:%S")
        )

    def refresh_dashboard(self):
        if self.refresh_button is not None:
            self.refresh_button.configure(
                state="disabled",
                text="Refreshing..."
            )

        self.update_idletasks()

        try:
            self.load_metrics()
            self.rebuild_dynamic_sections()

        finally:
            if self.refresh_button is not None:
                self.refresh_button.configure(
                    state="normal",
                    text="↻  Refresh"
                )

    def rebuild_dynamic_sections(self):
        # Recreate the scrollable content so every live metric,
        # queue row and capacity visual stays internally consistent.
        for widget in self.main.winfo_children():
            widget.destroy()

        self.create_header()
        self.create_kpi_row()
        self.create_operational_row()
        self.create_capacity_and_quality_row()
        self.create_quick_actions()
        self.create_footer()

    def go_patients(self):
        if hasattr(self.window, "show_patients"):
            self.window.show_patients()

    def go_appointments(self):
        if hasattr(self.window, "show_appointments"):
            self.window.show_appointments()

    def go_reports(self):
        if hasattr(self.window, "show_reports"):
            self.window.show_reports()

    def go_performance(self):
        if hasattr(self.window, "show_performance"):
            self.window.show_performance()


if __name__ == "__main__":
    ctk.set_appearance_mode("light")
    ctk.set_default_color_theme("blue")

    root = ctk.CTk()
    root.title("MediCare Hospital Management System - Dashboard")
    root.geometry("1440x900")
    root.minsize(1180, 760)

    frame = DashboardFrame(
        root,
        {
            "user_id": 1,
            "username": "admin",
            "role": "admin"
        }
    )
    frame.pack(fill="both", expand=True)

    root.mainloop()
